Default: &defaults
  database: squatPal.sqlite3
  poolsize: 10

Development:
  <<: *defaults

Testing:
  database: squatPal_test.sqlite3
  <<: *defaults

Staging:
  database: squatPal_staging.sqlite3
  poolsize: 100
  <<: *defaults

Production:
  database: squatPal_production.sqlite3
  poolsize: 100
  <<: *defaults
